cask_args appdir: '/Applications'

brew 'homebrew/php/composer'
brew 'rbenv'
brew 'htop'
brew 'nmap'
brew 'ansible'
brew 'wpscan'
brew 'terraform'

cask 'atom'
cask 'charles'
cask 'dash'
cask 'firefox'
cask 'google-chrome'
cask 'hockey'
cask 'lastpass'
cask 'mailmate'
cask 'postman'
cask 'sequel-pro'
cask 'slack'
cask 'sourcetree'
cask 'spamsieve'
cask 'transmit'
cask 'virtualbox'
cask 'vlc'
